// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtmpALSJ6UW7Abz3IZmLuJ9calKsy2dpo',
    appId: '1:80535706366:web:d5a1ba8ab8f3f07e6fa3af',
    messagingSenderId: '80535706366',
    projectId: 'pharmacy-talk',
    authDomain: 'pharmacy-talk.firebaseapp.com',
    storageBucket: 'pharmacy-talk.appspot.com',
    measurementId: 'G-56HKQ1KP2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq1ZN9AQpy1enEKgAe9aZEOXPWYo_f2cg',
    appId: '1:80535706366:android:ae61433f0f5b516a6fa3af',
    messagingSenderId: '80535706366',
    projectId: 'pharmacy-talk',
    storageBucket: 'pharmacy-talk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmgpVwcLF-mVEqJR3hdgHDe8oA-Ag6_RY',
    appId: '1:80535706366:ios:714120f63383e2e16fa3af',
    messagingSenderId: '80535706366',
    projectId: 'pharmacy-talk',
    storageBucket: 'pharmacy-talk.appspot.com',
    iosBundleId: 'com.example.pharmacyTalk',
  );
}
